# Generated by Django 4.0.1 on 2022-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
