# Generated by Django 4.1.2 on 2022-12-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TG USERNAME'),
        ),
    ]
